name: nx4board
description: A Flutter app to show car info and get speed limits using GPS and open data.

publish_to: 'none'

version: 3.1.0+210

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # GPS & Location
  geolocator: ^10.1.0
  
  # CSV Parsing
  csv: ^6.0.0
  
  # Permission Handler
  permission_handler: ^12.0.1
  
  # State Management
  provider: ^6.1.0
  
  # UI
  cupertino_icons: ^1.0.2
  image: ^4.8.0
  package_info_plus: ^9.0.0
  web_socket_channel: ^3.0.3
  battery_plus: ^7.0.0
  wakelock_plus: ^1.4.0
  flutter_foreground_task: ^9.2.1
  shared_preferences: ^2.5.4
  path_provider: ^2.1.2
  share_plus: ^10.1.0
  intl: ^0.19.0
  flutter_tts: ^4.2.2
  volume_controller: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/省道速限圖資.csv
    - assets/camera_data.csv
    - assets/cd.html
    - assets/tailwind.min.js
    - assets/fonts/
    - assets/highway_landmarks.json
    - assets/expressway_landmarks.json

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/app_icon.png"
